Split sekiban core into Sekiban.Core.Neutral and Sekiban.Core.AspNetCore
J-Tech-Japan/Sekiban pull request #471
Opened 2024-12-25 02:25 UTC by info-miura

## What type of PR is this? (check all applicable)

- [x] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
This PR splits `Sekiban.Core` into `Sekiban.Core.Neutral` and `Sekiban.Core.AspNetCore`.
`Sekiban.Core.Neutral` no longer depends on `Microsoft.AspNetCore.App`, so it can be used in more restricted configurations.

## Related Tickets & Documents

- Related Issue #
- Closes #

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._

## Added/updated tests?
_We encourage you to keep the code coverage percentage at 80% and above._

- [ ] Yes
- [x] No, and this is why: This PR would only split package and move implementations. Therefore, it might be sufficient to pass existing tests.
- [ ] I need help with writing tests

## [optional] Are there any post deployment tasks we need to perform?
Which implementation of `IUserInformationFactory` should be used without depending on `Microsoft.AspNetCore.App`?

## [optional] What gif best describes this PR or how it makes you feel?

2024-12-26 00:23 UTC, tomohisa requested changes
@info-miura , Thank you for the great work!

After the consideration with @tkawae , we recommend following project structure.

Rename Sekiban.Core.Neutral -> Sekiban.Core.DotNet - and it will be released as nuget
Rename Sekiban.Core.AspNetCore -> Sekiban.Core - and it will be released as nuget

Remove Sekiban.Core - it is same with Sekiban.Core.AspNetCore now.

In future release, current Sekiban.Pure will be main sekiban, and we will consider naming by then.

2024-12-26 10:25 UTC, info-miura commented
Moved `Sekiban.Core.Neutral` to `Sekiban.Core.DotNet` and `Sekiban.Core.AspNetCore` to `Sekiban.Core`.
And also moved some AspNetCore dependent implementations to `Sekiban.Core`.

2024-12-28 03:35 UTC, tomohisa approved these changes

2024-12-28 03:35 UTC, tomohisa commented on src/Sekiban.Core/Dependency/SekibanAspNetCoreEventSourcingDependency.cs
> +                typeof(UpdateNoticeEventSubscriber<>).Assembly)); // Sekiban.Core.DotNet needs to be added
Sekiban.Core.DotNet のAssemblyが登録されていないため、エラーで落ちていました。追加して、問題がなくなったら許可してマージします。

2024-12-28 05:05 UTC, merged